import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class UserAdminCreate {
  @ApiProperty()
  documentID: string;
}

export class UserAdmin {
  @ApiProperty()
  id: number;
  @ApiProperty()
  documentID: string;
}
