/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { UserAdmin } from './UserAdmin.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { UserAdminService } from './UserAdmin.service';
import { UserAdminController } from './UserAdmin.controller';

@Module({
  imports: [TypeOrmModule.forFeature([UserAdmin])],
  providers: [UserAdminService],
  exports: [UserAdminService],
  controllers: [UserAdminController],
})
export class UserAdminModule {}
