/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { UserAdmin, UserAdminCreate } from './dtos/UserAdmin.dto';
import { UserAdminController } from './UserAdmin.controller';
import { UserAdminService } from './UserAdmin.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('UserAdminController', () => {
  let controller: UserAdminController;
  let spyService: UserAdminService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: UserAdminService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [UserAdminController],
      providers: [UserAdminService, ApiServiceProvider],
    }).compile();

    controller = module.get<UserAdminController>(UserAdminController);
    spyService = module.get<UserAdminService>(UserAdminService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call UserAdminController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call UserAdminController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new UserAdmin();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
