/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { UserData } from './UserData.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { UserDataService } from './UserData.service';
import { UserDataController } from './UserData.controller';

@Module({
  imports: [TypeOrmModule.forFeature([UserData])],
  providers: [UserDataService],
  exports: [UserDataService],
  controllers: [UserDataController],
})
export class UserDataModule {}
