/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { UserData, UserDataCreate } from './dtos/UserData.dto';
import { UserDataController } from './UserData.controller';
import { UserDataService } from './UserData.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('UserDataController', () => {
  let controller: UserDataController;
  let spyService: UserDataService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: UserDataService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [UserDataController],
      providers: [UserDataService, ApiServiceProvider],
    }).compile();

    controller = module.get<UserDataController>(UserDataController);
    spyService = module.get<UserDataService>(UserDataService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call UserDataController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call UserDataController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new UserData();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
