/**
 * This file generated by Apso.
 */
import { InsuranceDocumentModule } from './InsuranceDocument/InsuranceDocument.module';
import { UserAdminModule } from './UserAdmin/UserAdmin.module';
import { UserDataModule } from './UserData/UserData.module';

export default [InsuranceDocumentModule, UserAdminModule, UserDataModule];
