import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class UserDataCreate {
  @ApiProperty()
  userDataField: string;
  @ApiProperty()
  FNAME: string;
  @ApiProperty()
  LNAME: string;
  @ApiProperty()
  EMAIL: string;
  @ApiProperty()
  SSN: string;
  @ApiProperty()
  TITLE: string;
}

export class UserData {
  @ApiProperty()
  id: number;
  @ApiProperty()
  userDataField: string;
  @ApiProperty()
  FNAME: string;
  @ApiProperty()
  LNAME: string;
  @ApiProperty()
  EMAIL: string;
  @ApiProperty()
  SSN: string;
  @ApiProperty()
  TITLE: string;
}
