import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class InsuranceDocumentCreate {
  @ApiProperty()
  documentData: string;
  @ApiProperty()
  parsedData: string;
  @ApiProperty()
  LLMsUsed: string;
  @ApiProperty()
  CRUDInterface: string;
}

export class InsuranceDocument {
  @ApiProperty()
  id: number;
  @ApiProperty()
  documentData: string;
  @ApiProperty()
  parsedData: string;
  @ApiProperty()
  LLMsUsed: string;
  @ApiProperty()
  CRUDInterface: string;
}
