/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { InsuranceDocument } from './InsuranceDocument.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { InsuranceDocumentService } from './InsuranceDocument.service';
import { InsuranceDocumentController } from './InsuranceDocument.controller';

@Module({
  imports: [TypeOrmModule.forFeature([InsuranceDocument])],
  providers: [InsuranceDocumentService],
  exports: [InsuranceDocumentService],
  controllers: [InsuranceDocumentController],
})
export class InsuranceDocumentModule {}
