/**
 * This file generated by Apso.
 */
import { Controller } from '@nestjs/common';
import {
  Crud,
  CrudController,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
  CreateManyDto,
} from '@nestjsx/crud';
import { ApiTags, ApiResponse, ApiOperation, ApiBody } from '@nestjs/swagger';
import {
  InsuranceDocument,
  InsuranceDocumentCreate,
} from './dtos/InsuranceDocument.dto';
import { InsuranceDocumentService } from './InsuranceDocument.service';

@Crud({
  model: {
    type: InsuranceDocument,
  },
  dto: {
    create: InsuranceDocumentCreate,
    update: InsuranceDocument,
    replace: InsuranceDocument,
  },
  query: {
    /**
     * commenting out limit and pagination because of an issue with Crud lib: https://github.com/nestjsx/crud/issues/777
     */
    // TODO: make limit env driven?
    limit: 5,
    alwaysPaginate: true,
  },
})
@Controller('InsuranceDocuments')
@ApiTags('InsuranceDocuments')
export class InsuranceDocumentController implements CrudController<InsuranceDocument> {
  constructor(public service: InsuranceDocumentService) {}

  get base(): CrudController<InsuranceDocument> {
    return this;
  }

  @Override('getManyBase')
  @ApiOperation({ summary: 'Retrieve multiple InsuranceDocuments' })
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase(req);
  }

  @Override('getOneBase')
  @ApiOperation({ summary: 'Retrieve a single InsuranceDocument' })
  get(@ParsedRequest() req: CrudRequest) {
    return this.base.getOneBase(req);
  }

  @Override('createOneBase')
  @ApiOperation({ summary: 'Create a single InsuranceDocument' })
  @ApiBody({
    type: InsuranceDocumentCreate,
    description:
      'The Description for the Post Body. Please look into the DTO. You will see the @ApiOptionalProperty used to define the Schema.',
  })
  create(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: InsuranceDocument,
  ) {
    return this.base.createOneBase(req, dto);
  }

  @Override('createManyBase')
  @ApiOperation({ summary: 'Create multipleInsuranceDocuments' })
  createMany(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CreateManyDto<InsuranceDocument>,
  ) {
    return this.base.createManyBase(req, dto);
  }

  @Override('updateOneBase')
  @ApiOperation({ summary: 'Update a single InsuranceDocument' })
  update(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: InsuranceDocument,
  ) {
    return this.base.updateOneBase(req, dto);
  }

  @Override('replaceOneBase')
  @ApiOperation({ summary: 'Replace a single InsuranceDocument' })
  replace(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: InsuranceDocument,
  ) {
    return this.base.replaceOneBase(req, dto);
  }

  @Override('deleteOneBase')
  @ApiOperation({ summary: 'Delete a single InsuranceDocument' })
  delete(@ParsedRequest() req: CrudRequest) {
    return this.base.deleteOneBase(req);
  }
}
