/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import {
  InsuranceDocument,
  InsuranceDocumentCreate,
} from './dtos/InsuranceDocument.dto';
import { InsuranceDocumentController } from './InsuranceDocument.controller';
import { InsuranceDocumentService } from './InsuranceDocument.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('InsuranceDocumentController', () => {
  let controller: InsuranceDocumentController;
  let spyService: InsuranceDocumentService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: InsuranceDocumentService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [InsuranceDocumentController],
      providers: [InsuranceDocumentService, ApiServiceProvider],
    }).compile();

    controller = module.get<InsuranceDocumentController>(
      InsuranceDocumentController,
    );
    spyService = module.get<InsuranceDocumentService>(InsuranceDocumentService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call InsuranceDocumentController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call InsuranceDocumentController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new InsuranceDocument();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
